# docker-compose.yml

services:
  deliveries-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: deliveries-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development